import Foundation

typealias ManufacturerInformation = [String: (String, String, Manufacturer.Group)]

let manufacturerInformation: ManufacturerInformation = [
    "01": ("Sequential Circuits", "Sequential Circuits", .american),
    "02": ("IDP", "IDP", .american),
    "03": ("Voyetra Turtle Beach, Inc.", "Voyetra Turtle Beach, Inc.", .american),
    "04": ("Moog Music", "Moog Music", .american),
    "05": ("Passport Designs", "Passport Designs", .american),
    "06": ("Lexicon Inc.", "Lexicon Inc.", .american),
    "07": ("Kurzweil / Young Chang", "Kurzweil / Young Chang", .american),
    "08": ("Fender", "Fender", .american),
    "09": ("MIDI9", "MIDI9", .american),
    "0A": ("AKG Acoustics", "AKG Acoustics", .american),
    "0B": ("Voyce Music", "Voyce Music", .american),
    "0C": ("WaveFrame (Timeline)", "WaveFrame (Timeline)", .american),
    "0D": ("ADA Signal Processors, Inc.", "ADA Signal Processors, Inc.", .american),
    "0E": ("Garfield Electronics", "Garfield Electronics", .american),
    "0F": ("Ensoniq", "Ensoniq", .american),
    "10": ("Oberheim / Gibson Labs", "Oberheim / Gibson Labs", .american),
    "11": ("Apple", "Apple", .american),
    "12": ("Grey Matter Response", "Grey Matter Response", .american),
    "13": ("Digidesign Inc.", "Digidesign Inc.", .american),
    "14": ("Palmtree Instruments", "Palmtree Instruments", .american),
    "15": ("JLCooper Electronics", "JLCooper Electronics", .american),
    "16": ("Lowrey Organ Company", "Lowrey Organ Company", .american),
    "17": ("Adams-Smith", "Adams-Smith", .american),
    "18": ("E-mu", "E-mu", .american),
    "19": ("Harmony Systems", "Harmony Systems", .american),
    "1A": ("ART", "ART", .american),
    "1B": ("Baldwin", "Baldwin", .american),
    "1C": ("Eventide", "Eventide", .american),
    "1D": ("Inventronics", "Inventronics", .american),
    "1E": ("Key Concepts", "Key Concepts", .american),
    "1F": ("Clarity", "Clarity", .american),
    "20": ("Passac", "Passac", .american),
    "21": ("Proel Labs (SIEL)", "Proel Labs (SIEL)", .american),
    "22": ("Synthaxe (UK)", "Synthaxe (UK)", .american),
    "23": ("Stepp", "Stepp", .american),
    "24": ("Hohner", "Hohner", .american),
    "25": ("Twister", "Twister", .american),
    "26": ("Ketron s.r.l.", "Ketron s.r.l.", .american),
    "27": ("Jellinghaus MS", "Jellinghaus MS", .american),
    "28": ("Southworth Music Systems", "Southworth Music Systems", .american),
    "29": ("PPG (Germany)", "PPG (Germany)", .american),
    "2A": ("JEN", "JEN", .american),
    "2B": ("Solid State Logic Organ Systems", "Solid State Logic Organ Systems", .american),
    "2C": ("Audio Veritrieb-P. Struven", "Audio Veritrieb-P. Struven", .american),
    "2D": ("Neve", "Neve", .american),
    "2E": ("Soundtracs Ltd.", "Soundtracs Ltd.", .american),
    "2F": ("Elka", "Elka", .american),
    "30": ("Dynacord", "Dynacord", .american),
    "31": ("None", "None", .american),
    "32": ("Drawmer", "Drawmer", .american),
    "33": ("Clavia Digital Instruments", "Clavia Digital Instruments", .american),
    "34": ("Audio Architecture", "Audio Architecture", .american),
    "35": ("Generalmusic Corp SpA", "Generalmusic Corp SpA", .american),
    "36": ("Cheetah Marketing", "Cheetah Marketing", .american),
    "37": ("C.T.M.", "C.T.M.", .american),
    "38": ("Simmons UK", "Simmons UK", .american),
    "39": ("Soundcraft Electronics", "Soundcraft Electronics", .american),
    "3A": ("Steinberg Media Technologies GmbH", "Steinberg Media Technologies GmbH", .american),
    "3B": ("Wersi Gmbh", "Wersi Gmbh", .american),
    "3C": ("AVAB Niethammer AB", "AVAB Niethammer AB", .american),
    "3D": ("Digigram", "Digigram", .american),
    "3E": ("Waldorf Electronics GmbH", "Waldorf Electronics GmbH", .american),
    "3F": ("Quasimidi", "Quasimidi", .american),
    "000001": ("Time/Warner Interactive", "Time/Warner Interactive", .american),
    "000002": ("Advanced Gravis Comp. Tech Ltd.", "Advanced Gravis Comp. Tech Ltd.", .american),
    "000003": ("Media Vision", "Media Vision", .american),
    "000004": ("Dornes Research Group", "Dornes Research Group", .american),
    "000005": ("K-Muse", "K-Muse", .american),
    "000006": ("Stypher", "Stypher", .american),
    "000007": ("Digital Music Corp.", "Digital Music Corp.", .american),
    "000008": ("IOTA Systems", "IOTA Systems", .american),
    "000009": ("New England Digital", "New England Digital", .american),
    "00000A": ("Artisyn", "Artisyn", .american),
    "00000B": ("IVL Technologies Ltd.", "IVL Technologies Ltd.", .american),
    "00000C": ("Southern Music Systems", "Southern Music Systems", .american),
    "00000D": ("Lake Butler Sound Company", "Lake Butler Sound Company", .american),
    "00000E": ("Alesis Studio Electronics", "Alesis Studio Electronics", .american),
    "00000F": ("Sound Creation", "Sound Creation", .american),
    "000010": ("DOD Electronics Corp.", "DOD Electronics Corp.", .american),
    "000011": ("Studer-Editech", "Studer-Editech", .american),
    "000012": ("Sonus", "Sonus", .american),
    "000013": ("Temporal Acuity Products", "Temporal Acuity Products", .american),
    "000014": ("Perfect Fretworks", "Perfect Fretworks", .american),
    "000015": ("KAT Inc.", "KAT Inc.", .american),
    "000016": ("Opcode Systems", "Opcode Systems", .american),
    "000017": ("Rane Corporation", "Rane Corporation", .american),
    "000018": ("Anadi Electronique", "Anadi Electronique", .american),
    "000019": ("KMX", "KMX", .american),
    "00001A": ("Allen & Heath Brenell", "Allen & Heath Brenell", .american),
    "00001B": ("Peavey Electronics", "Peavey Electronics", .american),
    "00001C": ("360 Systems", "360 Systems", .american),
    "00001D": ("Spectrum Design and Development", "Spectrum Design and Development", .american),
    "00001E": ("Marquis Music", "Marquis Music", .american),
    "00001F": ("Zeta Systems", "Zeta Systems", .american),
    "000020": ("Axxes (Brian Parsonett)", "Axxes (Brian Parsonett)", .american),
    "000021": ("Orban", "Orban", .american),
    "000022": ("Indian Valley Mfg.", "Indian Valley Mfg.", .american),
    "000023": ("Triton", "Triton", .american),
    "000024": ("KTI", "KTI", .american),
    "000025": ("Breakaway Technologies", "Breakaway Technologies", .american),
    "000026": ("Leprecon / CAE Inc.", "Leprecon / CAE Inc.", .american),
    "000027": ("Harrison Systems Inc.", "Harrison Systems Inc.", .american),
    "000028": ("Future Lab/Mark Kuo", "Future Lab/Mark Kuo", .american),
    "000029": ("Rocktron Corporation", "Rocktron Corporation", .american),
    "00002A": ("PianoDisc", "PianoDisc", .american),
    "00002B": ("Cannon Research Group", "Cannon Research Group", .american),
    "00002C": ("Reserved", "Reserved", .american),
    "00002D": ("Rodgers Instrument LLC", "Rodgers Instrument LLC", .american),
    "00002E": ("Blue Sky Logic", "Blue Sky Logic", .american),
    "00002F": ("Encore Electronics", "Encore Electronics", .american),
    "000030": ("Uptown", "Uptown", .american),
    "000031": ("Voce", "Voce", .american),
    "000032": ("CTI Audio, Inc. (Musically Intel. Devs.)", "CTI Audio, Inc. (Musically Intel. Devs.)", .american),
    "000033": ("S3 Incorporated", "S3 Incorporated", .american),
    "000034": ("Broderbund / Red Orb", "Broderbund / Red Orb", .american),
    "000035": ("Allen Organ Co.", "Allen Organ Co.", .american),
    "000036": ("Reserved", "Reserved", .american),
    "000037": ("Music Quest", "Music Quest", .american),
    "000038": ("Aphex", "Aphex", .american),
    "000039": ("Gallien Krueger", "Gallien Krueger", .american),
    "00003A": ("IBM", "IBM", .american),
    "00003B": ("Mark Of The Unicorn", "Mark Of The Unicorn", .american),
    "00003C": ("Hotz Corporation", "Hotz Corporation", .american),
    "00003D": ("ETA Lighting", "ETA Lighting", .american),
    "00003E": ("NSI Corporation", "NSI Corporation", .american),
    "00003F": ("Ad Lib, Inc.", "Ad Lib, Inc.", .american),
    "000040": ("Richmond Sound Design", "Richmond Sound Design", .american),
    "000041": ("Microsoft", "Microsoft", .american),
    "000042": ("Mindscape (Software Toolworks)", "Mindscape (Software Toolworks)", .american),
    "000043": ("Russ Jones Marketing / Niche", "Russ Jones Marketing / Niche", .american),
    "000044": ("Intone", "Intone", .american),
    "000045": ("Advanced Remote Technologies", "Advanced Remote Technologies", .american),
    "000046": ("White Instruments", "White Instruments", .american),
    "000047": ("GT Electronics/Groove Tubes", "GT Electronics/Groove Tubes", .american),
    "000048": ("Pacific Research & Engineering", "Pacific Research & Engineering", .american),
    "000049": ("Timeline Vista, Inc.", "Timeline Vista, Inc.", .american),
    "00004A": ("Mesa Boogie Ltd.", "Mesa Boogie Ltd.", .american),
    "00004B": ("FSLI", "FSLI", .american),
    "00004C": ("Sequoia Development Group", "Sequoia Development Group", .american),
    "00004D": ("Studio Electronics", "Studio Electronics", .american),
    "00004E": ("Euphonix, Inc", "Euphonix, Inc", .american),
    "00004F": ("InterMIDI, Inc.", "InterMIDI, Inc.", .american),
    "000050": ("MIDI Solutions Inc.", "MIDI Solutions Inc.", .american),
    "000051": ("3DO Company", "3DO Company", .american),
    "000052": ("Lightwave Research / High End Systems", "Lightwave Research / High End Systems", .american),
    "000053": ("Micro-W Corporation", "Micro-W Corporation", .american),
    "000054": ("Spectral Synthesis, Inc.", "Spectral Synthesis, Inc.", .american),
    "000055": ("Lone Wolf", "Lone Wolf", .american),
    "000056": ("Studio Technologies Inc.", "Studio Technologies Inc.", .american),
    "000057": ("Peterson Electro-Musical Product, Inc.", "Peterson Electro-Musical Product, Inc.", .american),
    "000058": ("Atari Corporation", "Atari Corporation", .american),
    "000059": ("Marion Systems Corporation", "Marion Systems Corporation", .american),
    "00005A": ("Design Event", "Design Event", .american),
    "00005B": ("Winjammer Software Ltd.", "Winjammer Software Ltd.", .american),
    "00005C": ("AT&T Bell Laboratories", "AT&T Bell Laboratories", .american),
    "00005D": ("Reserved", "Reserved", .american),
    "00005E": ("Symetrix", "Symetrix", .american),
    "00005F": ("MIDI the World", "MIDI the World", .american),
    "000060": ("Spatializer", "Spatializer", .american),
    "000061": ("Micros 'N MIDI", "Micros 'N MIDI", .american),
    "000062": ("Accordians International", "Accordians International", .american),
    "000063": ("EuPhonics (now 3Com)", "EuPhonics (now 3Com)", .american),
    "000064": ("Musonix", "Musonix", .american),
    "000065": ("Turtle Beach Systems (Voyetra)", "Turtle Beach Systems (Voyetra)", .american),
    "000066": ("Loud Technologies / Mackie", "Loud Technologies / Mackie", .american),
    "000067": ("Compuserve", "Compuserve", .american),
    "000068": ("BEC Technologies", "BEC Technologies", .american),
    "000069": ("QRS Music Inc", "QRS Music Inc", .american),
    "00006A": ("P.G. Music", "P.G. Music", .american),
    "00006B": ("Sierra Semiconductor", "Sierra Semiconductor", .american),
    "00006C": ("EpiGraf", "EpiGraf", .american),
    "00006D": ("Electronics Diversified Inc", "Electronics Diversified Inc", .american),
    "00006E": ("Tune 1000", "Tune 1000", .american),
    "00006F": ("Advanced Micro Devices", "Advanced Micro Devices", .american),
    "000070": ("Mediamation", "Mediamation", .american),
    "000071": ("Sabine Musical Mfg. Co. Inc.", "Sabine Musical Mfg. Co. Inc.", .american),
    "000072": ("Woog Labs", "Woog Labs", .american),
    "000073": ("Micropolis Corp", "Micropolis Corp", .american),
    "000074": ("Ta Horng Musical Instrument", "Ta Horng Musical Instrument", .american),
    "000075": ("e-Tek Labs (Forte Tech)", "e-Tek Labs (Forte Tech)", .american),
    "000076": ("Electro-Voice", "Electro-Voice", .american),
    "000077": ("Midisoft Corporation", "Midisoft Corporation", .american),
    "000078": ("QSound Labs", "QSound Labs", .american),
    "000079": ("Westrex", "Westrex", .american),
    "00007A": ("Nvidia", "Nvidia", .american),
    "00007B": ("ESS Technology", "ESS Technology", .american),
    "00007C": ("Media Trix Peripherals", "Media Trix Peripherals", .american),
    "00007D": ("Brooktree Corp", "Brooktree Corp", .american),
    "00007E": ("Otari Corp", "Otari Corp", .american),
    "00007F": ("Key Electronics, Inc.", "Key Electronics, Inc.", .american),
    "000100": ("Shure Incorporated", "Shure Incorporated", .american),
    "000101": ("AuraSound", "AuraSound", .american),
    "000102": ("Crystal Semiconductor", "Crystal Semiconductor", .american),
    "000103": ("Conexant (Rockwell)", "Conexant (Rockwell)", .american),
    "000104": ("Silicon Graphics", "Silicon Graphics", .american),
    "000105": ("M-Audio (Midiman)", "M-Audio (Midiman)", .american),
    "000106": ("PreSonus", "PreSonus", .american),
    "000108": ("Topaz Enterprises", "Topaz Enterprises", .american),
    "000109": ("Cast Lighting", "Cast Lighting", .american),
    "00010A": ("Microsoft Consumer Division", "Microsoft Consumer Division", .american),
    "00010B": ("Sonic Foundry", "Sonic Foundry", .american),
    "00010C": ("None", "None", .american),
    "00010D": ("Beatnik Inc", "Beatnik Inc", .american),
    "00010E": ("Van Koevering Company", "Van Koevering Company", .american),
    "00010F": ("Altech Systems", "Altech Systems", .american),
    "000110": ("S & S Research", "S & S Research", .american),
    "000111": ("VLSI Technology", "VLSI Technology", .american),
    "000112": ("Chromatic Research", "Chromatic Research", .american),
    "000113": ("Sapphire", "Sapphire", .american),
    "000114": ("IDRC", "IDRC", .american),
    "000115": ("Justonic Tuning", "Justonic Tuning", .american),
    "000116": ("TorComp Research Inc.", "TorComp Research Inc.", .american),
    "000117": ("Newtek Inc.", "Newtek Inc.", .american),
    "000118": ("Sound Sculpture", "Sound Sculpture", .american),
    "000119": ("Walker Technical", "Walker Technical", .american),
    "00011A": ("Digital Harmony (PAVO)", "Digital Harmony (PAVO)", .american),
    "00011B": ("InVision Interactive", "InVision Interactive", .american),
    "00011C": ("T-Square Design", "T-Square Design", .american),
    "00011D": ("Nemesys Music Technology", "Nemesys Music Technology", .american),
    "00011E": ("DBX Professional (Harman Intl)", "DBX Professional (Harman Intl)", .american),
    "00011F": ("Syndyne Corporation", "Syndyne Corporation", .american),
    "000120": ("Bitheadz", "Bitheadz", .american),
    "000121": ("BandLab Technologies", "BandLab Technologies", .american),
    "000122": ("Analog Devices", "Analog Devices", .american),
    "000123": ("National Semiconductor", "National Semiconductor", .american),
    "000124": ("Boom Theory / Adinolfi Alternative Percussion", "Boom Theory / Adinolfi Alternative Percussion", .american),
    "000125": ("Virtual DSP Corporation", "Virtual DSP Corporation", .american),
    "000126": ("Antares Systems", "Antares Systems", .american),
    "000127": ("Angel Software", "Angel Software", .american),
    "000128": ("St Louis Music", "St Louis Music", .american),
    "000129": ("Passport Music Software LLC (Gvox)", "Passport Music Software LLC (Gvox)", .american),
    "00012A": ("Ashley Audio Inc.", "Ashley Audio Inc.", .american),
    "00012B": ("Vari-Lite Inc.", "Vari-Lite Inc.", .american),
    "00012C": ("Summit Audio Inc.", "Summit Audio Inc.", .american),
    "00012D": ("Aureal Semiconductor Inc.", "Aureal Semiconductor Inc.", .american),
    "00012E": ("SeaSound LLC", "SeaSound LLC", .american),
    "00012F": ("U.S. Robotics", "U.S. Robotics", .american),
    "000130": ("Aurisis Research", "Aurisis Research", .american),
    "000131": ("Nearfield Research", "Nearfield Research", .american),
    "000132": ("FM7 Inc", "FM7 Inc", .american),
    "000133": ("Swivel Systems", "Swivel Systems", .american),
    "000134": ("Hyperactive Audio Systems", "Hyperactive Audio Systems", .american),
    "000135": ("MidiLite (Castle Studios Productions)", "MidiLite (Castle Studios Productions)", .american),
    "000136": ("Radikal Technologies", "Radikal Technologies", .american),
    "000137": ("Roger Linn Design", "Roger Linn Design", .american),
    "000138": ("TC-Helicon Vocal Technologies", "TC-Helicon Vocal Technologies", .american),
    "000139": ("Event Electronics", "Event Electronics", .american),
    "00013A": ("Sonic Network Inc", "Sonic Network Inc", .american),
    "00013B": ("Realtime Music Solutions", "Realtime Music Solutions", .american),
    "00013C": ("Apogee Digital", "Apogee Digital", .american),
    "00013D": ("Classical Organs, Inc.", "Classical Organs, Inc.", .american),
    "00013E": ("Microtools Inc.", "Microtools Inc.", .american),
    "00013F": ("Numark Industries", "Numark Industries", .american),
    "000140": ("Frontier Design Group, LLC", "Frontier Design Group, LLC", .american),
    "000141": ("Recordare LLC", "Recordare LLC", .american),
    "000142": ("Starr Labs", "Starr Labs", .american),
    "000143": ("Voyager Sound Inc.", "Voyager Sound Inc.", .american),
    "000144": ("Manifold Labs", "Manifold Labs", .american),
    "000145": ("Aviom Inc.", "Aviom Inc.", .american),
    "000146": ("Mixmeister Technology", "Mixmeister Technology", .american),
    "000147": ("Notation Software", "Notation Software", .american),
    "000148": ("Mercurial Communications", "Mercurial Communications", .american),
    "000149": ("Wave Arts", "Wave Arts", .american),
    "00014A": ("Logic Sequencing Devices", "Logic Sequencing Devices", .american),
    "00014B": ("Axess Electronics", "Axess Electronics", .american),
    "00014C": ("Muse Research", "Muse Research", .american),
    "00014D": ("Open Labs", "Open Labs", .american),
    "00014E": ("Guillemot Corp", "Guillemot Corp", .american),
    "00014F": ("Samson Technologies", "Samson Technologies", .american),
    "000150": ("Electronic Theatre Controls", "Electronic Theatre Controls", .american),
    "000151": ("Blackberry (RIM)", "Blackberry (RIM)", .american),
    "000152": ("Mobileer", "Mobileer", .american),
    "000153": ("Synthogy", "Synthogy", .american),
    "000154": ("Lynx Studio Technology Inc.", "Lynx Studio Technology Inc.", .american),
    "000155": ("Damage Control Engineering LLC", "Damage Control Engineering LLC", .american),
    "000156": ("Yost Engineering, Inc.", "Yost Engineering, Inc.", .american),
    "000157": ("Brooks & Forsman Designs LLC / DrumLite", "Brooks & Forsman Designs LLC / DrumLite", .american),
    "000158": ("Infinite Response", "Infinite Response", .american),
    "000159": ("Garritan Corp", "Garritan Corp", .american),
    "00015A": ("Plogue Art et Technologie, Inc", "Plogue Art et Technologie, Inc", .american),
    "00015B": ("RJM Music Technology", "RJM Music Technology", .american),
    "00015C": ("Custom Solutions Software", "Custom Solutions Software", .american),
    "00015D": ("Sonarcana LLC / Highly Liquid", "Sonarcana LLC / Highly Liquid", .american),
    "00015E": ("Centrance", "Centrance", .american),
    "00015F": ("Kesumo LLC", "Kesumo LLC", .american),
    "000160": ("None", "None", .american),
    "000161": ("Livid Instruments", "Livid Instruments", .american),
    "000162": ("First Act / 745 Media", "First Act / 745 Media", .american),
    "000163": ("Pygraphics, Inc.", "Pygraphics, Inc.", .american),
    "000164": ("Panadigm Innovations Ltd", "Panadigm Innovations Ltd", .american),
    "000165": ("Avedis Zildjian Co", "Avedis Zildjian Co", .american),
    "000166": ("Auvital Music Corp", "Auvital Music Corp", .american),
    "000167": ("You Rock Guitar (was: Inspired Instruments)", "You Rock Guitar (was: Inspired Instruments)", .american),
    "000168": ("Chris Grigg Designs", "Chris Grigg Designs", .american),
    "000169": ("Slate Digital LLC", "Slate Digital LLC", .american),
    "00016A": ("Mixware", "Mixware", .american),
    "00016B": ("Social Entropy", "Social Entropy", .american),
    "00016C": ("Source Audio LLC", "Source Audio LLC", .american),
    "00016D": ("Ernie Ball / Music Man", "Ernie Ball / Music Man", .american),
    "00016E": ("Fishman", "Fishman", .american),
    "00016F": ("Custom Audio Electronics", "Custom Audio Electronics", .american),
    "000170": ("American Audio/DJ", "American Audio/DJ", .american),
    "000171": ("Mega Control Systems", "Mega Control Systems", .american),
    "000172": ("Kilpatrick Audio", "Kilpatrick Audio", .american),
    "000173": ("iConnectivity", "iConnectivity", .american),
    "000174": ("Fractal Audio", "Fractal Audio", .american),
    "000175": ("NetLogic Microsystems", "NetLogic Microsystems", .american),
    "000176": ("Music Computing", "Music Computing", .american),
    "000177": ("Nektar Technology Inc", "Nektar Technology Inc", .american),
    "000178": ("Zenph Sound Innovations", "Zenph Sound Innovations", .american),
    "000179": ("DJTechTools.com", "DJTechTools.com", .american),
    "00017A": ("Rezonance Labs", "Rezonance Labs", .american),
    "00017B": ("Decibel Eleven", "Decibel Eleven", .american),
    "00017C": ("CNMAT", "CNMAT", .american),
    "00017D": ("Media Overkill", "Media Overkill", .american),
    "00017E": ("Confusion Studios", "Confusion Studios", .american),
    "00017F": ("moForte Inc", "moForte Inc", .american),
    "000200": ("Miselu Inc", "Miselu Inc", .american),
    "000201": ("Amelia's Compass LLC", "Amelia's Compass LLC", .american),
    "000202": ("Zivix LLC", "Zivix LLC", .american),
    "000203": ("Artiphon", "Artiphon", .american),
    "000204": ("Synclavier Digital", "Synclavier Digital", .american),
    "000205": ("Light & Sound Control Devices LLC", "Light & Sound Control Devices LLC", .american),
    "000206": ("Retronyms Inc", "Retronyms Inc", .american),
    "000207": ("JS Technologies", "JS Technologies", .american),
    "000208": ("Quicco Sound", "Quicco Sound", .american),
    "000209": ("A-Designs Audio", "A-Designs Audio", .american),
    "00020A": ("McCarthy Music Corp", "McCarthy Music Corp", .american),
    "00020B": ("Denon DJ", "Denon DJ", .american),
    "00020C": ("Keith Robert Murray", "Keith Robert Murray", .american),
    "00020D": ("Google", "Google", .american),
    "00020E": ("ISP Technologies", "ISP Technologies", .american),
    "00020F": ("Abstrakt Instruments LLC", "Abstrakt Instruments LLC", .american),
    "000210": ("Meris LLC", "Meris LLC", .american),
    "000211": ("Sensorpoint LLC", "Sensorpoint LLC", .american),
    "000212": ("Hi-Z Labs", "Hi-Z Labs", .american),
    "000213": ("Imitone", "Imitone", .american),
    "000214": ("Intellijel Designs Inc.", "Intellijel Designs Inc.", .american),
    "000215": ("Dasz Instruments Inc.", "Dasz Instruments Inc.", .american),
    "000216": ("Remidi", "Remidi", .american),
    "000217": ("Disaster Area Designs LLC", "Disaster Area Designs LLC", .american),
    "000218": ("Universal Audio", "Universal Audio", .american),
    "000219": ("Carter Duncan Corp", "Carter Duncan Corp", .american),
    "00021A": ("Essential Technology", "Essential Technology", .american),
    "00021B": ("Cantux Research LLC", "Cantux Research LLC", .american),
    "00021C": ("Hummel Technologies", "Hummel Technologies", .american),
    "00021D": ("Sensel Inc", "Sensel Inc", .american),
    "00021E": ("DBML Group", "DBML Group", .american),
    "00021F": ("Madrona Labs", "Madrona Labs", .american),
    "000220": ("Mesa Boogie", "Mesa Boogie", .american),
    "000221": ("Effigy Labs", "Effigy Labs", .american),
    "000222": ("                              Amenote", "                              Amenote", .american),
    "000223": ("Red Panda LLC", "Red Panda LLC", .american),
    "000224": ("OnSong LLC", "OnSong LLC", .american),
    "000225": ("Jamboxx Inc.", "Jamboxx Inc.", .american),
    "000226": ("Electro-Harmonix ", "Electro-Harmonix ", .american),
    "000227": ("RnD64 Inc", "RnD64 Inc", .american),
    "000228": ("None", "None", .american),
    "000229": ("Kaom Inc.", "Kaom Inc.", .american),
    "00022A": ("Hallowell EMC", "Hallowell EMC", .american),
    "00022B": ("Sound Devices, LLC", "Sound Devices, LLC", .american),
    "00022C": ("Spectrasonics, Inc", "Spectrasonics, Inc", .american),
    "00022D": ("Second Sound, LLC", "Second Sound, LLC", .american),
    "00022E": ("8eo (Horn)", "8eo (Horn)", .american),
    "00022F": ("VIDVOX LLC", "VIDVOX LLC", .american),
    "000230": ("None", "None", .american),
    "002000": ("Dream SAS", "Dream SAS", .europeanOrOther),
    "002001": ("Strand Lighting", "Strand Lighting", .europeanOrOther),
    "002002": ("Amek Div of Harman Industries", "Amek Div of Harman Industries", .europeanOrOther),
    "002003": ("Casa Di Risparmio Di Loreto", "Casa Di Risparmio Di Loreto", .europeanOrOther),
    "002004": ("Böhm electronic GmbH", "Böhm electronic GmbH", .europeanOrOther),
    "002005": ("Syntec Digital Audio", "Syntec Digital Audio", .europeanOrOther),
    "002006": ("Trident Audio Developments", "Trident Audio Developments", .europeanOrOther),
    "002007": ("Real World Studio", "Real World Studio", .europeanOrOther),
    "002008": ("Evolution Synthesis, Ltd", "Evolution Synthesis, Ltd", .europeanOrOther),
    "002009": ("Yes Technology", "Yes Technology", .europeanOrOther),
    "00200A": ("Audiomatica", "Audiomatica", .europeanOrOther),
    "00200B": ("Bontempi SpA (Sigma)", "Bontempi SpA (Sigma)", .europeanOrOther),
    "00200C": ("F.B.T. Elettronica SpA", "F.B.T. Elettronica SpA", .europeanOrOther),
    "00200D": ("MidiTemp GmbH", "MidiTemp GmbH", .europeanOrOther),
    "00200E": ("LA Audio (Larking Audio)", "LA Audio (Larking Audio)", .europeanOrOther),
    "00200F": ("Zero 88 Lighting Limited", "Zero 88 Lighting Limited", .europeanOrOther),
    "002010": ("Micon Audio Electronics GmbH", "Micon Audio Electronics GmbH", .europeanOrOther),
    "002011": ("Forefront Technology", "Forefront Technology", .europeanOrOther),
    "002012": ("Studio Audio and Video Ltd.", "Studio Audio and Video Ltd.", .europeanOrOther),
    "002013": ("Kenton Electronics", "Kenton Electronics", .europeanOrOther),
    "002014": ("Celco/ Electrosonic", "Celco/ Electrosonic", .europeanOrOther),
    "002015": ("ADB", "ADB", .europeanOrOther),
    "002016": ("Marshall Products Limited", "Marshall Products Limited", .europeanOrOther),
    "002017": ("DDA", "DDA", .europeanOrOther),
    "002018": ("BSS Audio Ltd.", "BSS Audio Ltd.", .europeanOrOther),
    "002019": ("MA Lighting Technology", "MA Lighting Technology", .europeanOrOther),
    "00201A": ("Fatar SRL c/o Music Industries", "Fatar SRL c/o Music Industries", .europeanOrOther),
    "00201B": ("QSC Audio Products Inc.", "QSC Audio Products Inc.", .europeanOrOther),
    "00201C": ("Artisan Clasic Organ Inc.", "Artisan Clasic Organ Inc.", .europeanOrOther),
    "00201D": ("Orla Spa", "Orla Spa", .europeanOrOther),
    "00201E": ("Pinnacle Audio (Klark Teknik PLC)", "Pinnacle Audio (Klark Teknik PLC)", .europeanOrOther),
    "00201F": ("TC Electronics", "TC Electronics", .europeanOrOther),
    "002020": ("Doepfer Musikelektronik GmbH", "Doepfer Musikelektronik GmbH", .europeanOrOther),
    "002021": ("Creative ATC / E-mu", "Creative ATC / E-mu", .europeanOrOther),
    "002022": ("Seyddo/Minami", "Seyddo/Minami", .europeanOrOther),
    "002023": ("LG Electronics (Goldstar)", "LG Electronics (Goldstar)", .europeanOrOther),
    "002024": ("Midisoft sas di M.Cima & C", "Midisoft sas di M.Cima & C", .europeanOrOther),
    "002025": ("Samick Musical Inst. Co. Ltd.", "Samick Musical Inst. Co. Ltd.", .europeanOrOther),
    "002026": ("Penny and Giles (Bowthorpe PLC)", "Penny and Giles (Bowthorpe PLC)", .europeanOrOther),
    "002027": ("Acorn Computer", "Acorn Computer", .europeanOrOther),
    "002028": ("LSC Electronics Pty. Ltd.", "LSC Electronics Pty. Ltd.", .europeanOrOther),
    "002029": ("Focusrite/Novation", "Focusrite/Novation", .europeanOrOther),
    "00202A": ("Samkyung Mechatronics", "Samkyung Mechatronics", .europeanOrOther),
    "00202B": ("Medeli Electronics Co.", "Medeli Electronics Co.", .europeanOrOther),
    "00202C": ("Charlie Lab SRL", "Charlie Lab SRL", .europeanOrOther),
    "00202D": ("Blue Chip Music Technology", "Blue Chip Music Technology", .europeanOrOther),
    "00202E": ("BEE OH Corp", "BEE OH Corp", .europeanOrOther),
    "00202F": ("LG Semicon America", "LG Semicon America", .europeanOrOther),
    "002030": ("TESI", "TESI", .europeanOrOther),
    "002031": ("EMAGIC", "EMAGIC", .europeanOrOther),
    "002032": ("Behringer GmbH", "Behringer GmbH", .europeanOrOther),
    "002033": ("Access Music Electronics", "Access Music Electronics", .europeanOrOther),
    "002034": ("Synoptic", "Synoptic", .europeanOrOther),
    "002035": ("Hanmesoft", "Hanmesoft", .europeanOrOther),
    "002036": ("Terratec Electronic GmbH", "Terratec Electronic GmbH", .europeanOrOther),
    "002037": ("Proel SpA", "Proel SpA", .europeanOrOther),
    "002038": ("IBK MIDI", "IBK MIDI", .europeanOrOther),
    "002039": ("IRCAM", "IRCAM", .europeanOrOther),
    "00203A": ("Propellerhead Software", "Propellerhead Software", .europeanOrOther),
    "00203B": ("Red Sound Systems Ltd", "Red Sound Systems Ltd", .europeanOrOther),
    "00203C": ("Elektron ESI AB", "Elektron ESI AB", .europeanOrOther),
    "00203D": ("Sintefex Audio", "Sintefex Audio", .europeanOrOther),
    "00203E": ("MAM (Music and More)", "MAM (Music and More)", .europeanOrOther),
    "00203F": ("Amsaro GmbH", "Amsaro GmbH", .europeanOrOther),
    "002040": ("CDS Advanced Technology BV (Lanbox)", "CDS Advanced Technology BV (Lanbox)", .europeanOrOther),
    "002041": ("Mode Machines (Touched By Sound GmbH)", "Mode Machines (Touched By Sound GmbH)", .europeanOrOther),
    "002042": ("DSP Arts", "DSP Arts", .europeanOrOther),
    "002043": ("Phil Rees Music Tech", "Phil Rees Music Tech", .europeanOrOther),
    "002044": ("Stamer Musikanlagen GmbH", "Stamer Musikanlagen GmbH", .europeanOrOther),
    "002045": ("dba Soundart", "dba Soundart", .europeanOrOther),
    "002046": ("C-Mexx Software", "C-Mexx Software", .europeanOrOther),
    "002047": ("Klavis Technologies", "Klavis Technologies", .europeanOrOther),
    "002048": ("Noteheads AB", "Noteheads AB", .europeanOrOther),
    "002049": ("Algorithmix", "Algorithmix", .europeanOrOther),
    "00204A": ("Skrydstrup R&D", "Skrydstrup R&D", .europeanOrOther),
    "00204B": ("Professional Audio Company", "Professional Audio Company", .europeanOrOther),
    "00204C": ("NewWave Labs (MadWaves)", "NewWave Labs (MadWaves)", .europeanOrOther),
    "00204D": ("Vermona", "Vermona", .europeanOrOther),
    "00204E": ("Nokia", "Nokia", .europeanOrOther),
    "00204F": ("Wave Idea", "Wave Idea", .europeanOrOther),
    "002050": ("Hartmann GmbH", "Hartmann GmbH", .europeanOrOther),
    "002051": ("Lion's Tracs", "Lion's Tracs", .europeanOrOther),
    "002052": ("Analogue Systems", "Analogue Systems", .europeanOrOther),
    "002053": ("Focal-JMlab", "Focal-JMlab", .europeanOrOther),
    "002054": ("None", "None", .europeanOrOther),
    "002055": ("Faith Technologies (Digiplug)", "Faith Technologies (Digiplug)", .europeanOrOther),
    "002056": ("Showworks", "Showworks", .europeanOrOther),
    "002057": ("Manikin Electronic", "Manikin Electronic", .europeanOrOther),
    "002058": ("1 Come Tech", "1 Come Tech", .europeanOrOther),
    "002059": ("Phonic Corp", "Phonic Corp", .europeanOrOther),
    "00205A": ("Dolby Australia (Lake)", "Dolby Australia (Lake)", .europeanOrOther),
    "00205B": ("Silansys Technologies", "Silansys Technologies", .europeanOrOther),
    "00205C": ("Winbond Electronics", "Winbond Electronics", .europeanOrOther),
    "00205D": ("Cinetix Medien und Interface GmbH", "Cinetix Medien und Interface GmbH", .europeanOrOther),
    "00205E": ("A&G Soluzioni Digitali", "A&G Soluzioni Digitali", .europeanOrOther),
    "00205F": ("Sequentix GmbH", "Sequentix GmbH", .europeanOrOther),
    "002060": ("Oram Pro Audio", "Oram Pro Audio", .europeanOrOther),
    "002061": ("Be4 Ltd", "Be4 Ltd", .europeanOrOther),
    "002062": ("Infection Music", "Infection Music", .europeanOrOther),
    "002063": ("Central Music Co. (CME)", "Central Music Co. (CME)", .europeanOrOther),
    "002064": ("genoQs Machines GmbH", "genoQs Machines GmbH", .europeanOrOther),
    "002065": ("Medialon", "Medialon", .europeanOrOther),
    "002066": ("Waves Audio Ltd", "Waves Audio Ltd", .europeanOrOther),
    "002067": ("Jerash Labs", "Jerash Labs", .europeanOrOther),
    "002068": ("Da Fact", "Da Fact", .europeanOrOther),
    "002069": ("Elby Designs", "Elby Designs", .europeanOrOther),
    "00206A": ("Spectral Audio", "Spectral Audio", .europeanOrOther),
    "00206B": ("Arturia", "Arturia", .europeanOrOther),
    "00206C": ("Vixid", "Vixid", .europeanOrOther),
    "00206D": ("C-Thru Music", "C-Thru Music", .europeanOrOther),
    "00206E": ("Ya Horng Electronic Co LTD", "Ya Horng Electronic Co LTD", .europeanOrOther),
    "00206F": ("SM Pro Audio", "SM Pro Audio", .europeanOrOther),
    "002070": ("OTO Machines", "OTO Machines", .europeanOrOther),
    "002071": ("ELZAB S.A. (G LAB)", "ELZAB S.A. (G LAB)", .europeanOrOther),
    "002072": ("Blackstar Amplification Ltd", "Blackstar Amplification Ltd", .europeanOrOther),
    "002074": ("Gemalto (from Xiring)", "Gemalto (from Xiring)", .europeanOrOther),
    "002075": ("Prostage SL", "Prostage SL", .europeanOrOther),
    "002076": ("Teenage Engineering", "Teenage Engineering", .europeanOrOther),
    "002077": ("Tobias Erichsen Consulting", "Tobias Erichsen Consulting", .europeanOrOther),
    "002078": ("Nixer Ltd", "Nixer Ltd", .europeanOrOther),
    "002079": ("Hanpin Electron Co Ltd", "Hanpin Electron Co Ltd", .europeanOrOther),
    "00207A": ("\"MIDI-hardware\" R.Sowa", "\"MIDI-hardware\" R.Sowa", .europeanOrOther),
    "00207B": ("Beyond Music Industrial Ltd", "Beyond Music Industrial Ltd", .europeanOrOther),
    "00207C": ("Kiss Box B.V.", "Kiss Box B.V.", .europeanOrOther),
    "00207D": ("Misa Digital Technologies Ltd", "Misa Digital Technologies Ltd", .europeanOrOther),
    "00207E": ("AI Musics Technology Inc", "AI Musics Technology Inc", .europeanOrOther),
    "00207F": ("Serato Inc LP", "Serato Inc LP", .europeanOrOther),
    "002100": ("Limex", "Limex", .europeanOrOther),
    "002101": ("Kyodday (Tokai)", "Kyodday (Tokai)", .europeanOrOther),
    "002102": ("Mutable Instruments", "Mutable Instruments", .europeanOrOther),
    "002103": ("PreSonus Software Ltd", "PreSonus Software Ltd", .europeanOrOther),
    "002104": ("Ingenico (was Xiring)", "Ingenico (was Xiring)", .europeanOrOther),
    "002105": ("Fairlight Instruments Pty Ltd", "Fairlight Instruments Pty Ltd", .europeanOrOther),
    "002106": ("Musicom Lab", "Musicom Lab", .europeanOrOther),
    "002107": ("Modal Electronics (Modulus/VacoLoco)", "Modal Electronics (Modulus/VacoLoco)", .europeanOrOther),
    "002109": ("Native Instruments", "Native Instruments", .europeanOrOther),
    "00210A": ("Naonext", "Naonext", .europeanOrOther),
    "00210B": ("MFB", "MFB", .europeanOrOther),
    "00210C": ("Teknel Research", "Teknel Research", .europeanOrOther),
    "00210D": ("Ploytec GmbH", "Ploytec GmbH", .europeanOrOther),
    "00210E": ("Surfin Kangaroo Studio", "Surfin Kangaroo Studio", .europeanOrOther),
    "00210F": ("Philips Electronics HK Ltd", "Philips Electronics HK Ltd", .europeanOrOther),
    "002110": ("ROLI Ltd", "ROLI Ltd", .europeanOrOther),
    "002111": ("Panda-Audio Ltd", "Panda-Audio Ltd", .europeanOrOther),
    "002112": ("BauM Software", "BauM Software", .europeanOrOther),
    "002113": ("Machinewerks Ltd.", "Machinewerks Ltd.", .europeanOrOther),
    "002114": ("Xiamen Elane Electronics", "Xiamen Elane Electronics", .europeanOrOther),
    "002115": ("Marshall Amplification PLC", "Marshall Amplification PLC", .europeanOrOther),
    "002116": ("Kiwitechnics Ltd", "Kiwitechnics Ltd", .europeanOrOther),
    "002117": ("Rob Papen", "Rob Papen", .europeanOrOther),
    "002118": ("Spicetone OU", "Spicetone OU", .europeanOrOther),
    "002119": ("V3Sound", "V3Sound", .europeanOrOther),
    "00211A": ("IK Multimedia", "IK Multimedia", .europeanOrOther),
    "00211B": ("Novalia Ltd", "Novalia Ltd", .europeanOrOther),
    "00211C": ("Modor Music", "Modor Music", .europeanOrOther),
    "00211D": ("Ableton", "Ableton", .europeanOrOther),
    "00211E": ("Dtronics", "Dtronics", .europeanOrOther),
    "00211F": ("ZAQ Audio", "ZAQ Audio", .europeanOrOther),
    "002120": ("Muabaobao Education Technology Co Ltd", "Muabaobao Education Technology Co Ltd", .europeanOrOther),
    "002121": ("Flux Effects", "Flux Effects", .europeanOrOther),
    "002122": ("Audiothingies (MCDA)", "Audiothingies (MCDA)", .europeanOrOther),
    "002123": ("Retrokits", "Retrokits", .europeanOrOther),
    "002124": ("Morningstar FX Pte Ltd", "Morningstar FX Pte Ltd", .europeanOrOther),
    "002125": ("Changsha Hotone Audio Co Ltd", "Changsha Hotone Audio Co Ltd", .europeanOrOther),
    "002126": ("Expressive E", "Expressive E", .europeanOrOther),
    "002127": ("Expert Sleepers Ltd", "Expert Sleepers Ltd", .europeanOrOther),
    "002128": ("Timecode-Vision Technology", "Timecode-Vision Technology", .europeanOrOther),
    "002129": ("Hornberg Research GbR", "Hornberg Research GbR", .europeanOrOther),
    "00212A": ("Sonic Potions", "Sonic Potions", .europeanOrOther),
    "00212B": ("Audiofront", "Audiofront", .europeanOrOther),
    "00212C": ("Fred's Lab", "Fred's Lab", .europeanOrOther),
    "00212D": ("Audio Modeling", "Audio Modeling", .europeanOrOther),
    "00212E": ("C. Bechstein Digital GmbH", "C. Bechstein Digital GmbH", .europeanOrOther),
    "00212F": ("Motas Electronics Ltd", "Motas Electronics Ltd", .europeanOrOther),
    "002130": ("Elk Audio", "Elk Audio", .europeanOrOther),
    "002131": ("Sonic Academy Ltd", "Sonic Academy Ltd", .europeanOrOther),
    "002132": ("Bome Software", "Bome Software", .europeanOrOther),
    "002133": ("AODYO SAS", "AODYO SAS", .europeanOrOther),
    "002134": ("Pianoforce S.R.O", "Pianoforce S.R.O", .europeanOrOther),
    "002135": ("Dreadbox P.C.", "Dreadbox P.C.", .europeanOrOther),
    "002136": ("TouchKeys Instruments Ltd", "TouchKeys Instruments Ltd", .europeanOrOther),
    "002137": ("The Gigrig Ltd", "The Gigrig Ltd", .europeanOrOther),
    "002138": ("ALM Co", "ALM Co", .europeanOrOther),
    "002139": ("CH Sound Design", "CH Sound Design", .europeanOrOther),
    "00213A": ("Beat Bars", "Beat Bars", .europeanOrOther),
    "00213B": ("Blokas", "Blokas", .europeanOrOther),
    "00213C": ("GEWA Music GmbH", "GEWA Music GmbH", .europeanOrOther),
    "00213D": ("dadamachines", "dadamachines", .europeanOrOther),
    "00213E": ("Augmented Instruments Ltd (Bela)", "Augmented Instruments Ltd (Bela)", .europeanOrOther),
    "00213F": ("Supercritical Ltd", "Supercritical Ltd", .europeanOrOther),
    "002140": ("Genki Instruments", "Genki Instruments", .europeanOrOther),
    "002141": ("Marienberg Devices Germany", "Marienberg Devices Germany", .europeanOrOther),
    "002142": ("Supperware Ltd", "Supperware Ltd", .europeanOrOther),
    "002143": ("None", "None", .europeanOrOther),
    "002144": ("Swapp Technologies SRL", "Swapp Technologies SRL", .europeanOrOther),
    "002145": ("Electra One S.R.O.", "Electra One S.R.O.", .europeanOrOther),
    "002146": ("Digital Clef Limited", "Digital Clef Limited", .europeanOrOther),
    "002147": ("Paul Whittington Group Ltd", "Paul Whittington Group Ltd", .europeanOrOther),
    "40": ("Kawai Musical Instruments MFG. CO. Ltd", "Kawai Musical Instruments MFG. CO. Ltd", .japanese),
    "41": ("Roland Corporation", "Roland Corporation", .japanese),
    "42": ("Korg Inc.", "Korg Inc.", .japanese),
    "43": ("Yamaha Corporation", "Yamaha Corporation", .japanese),
    "44": ("Casio Computer Co. Ltd", "Casio Computer Co. Ltd", .japanese),
    "46": ("Kamiya Studio Co. Ltd", "Kamiya Studio Co. Ltd", .japanese),
    "47": ("Akai Electric Co. Ltd.", "Akai Electric Co. Ltd.", .japanese),
    "48": ("Victor Company of Japan, Ltd.", "Victor Company of Japan, Ltd.", .japanese),
    "4B": ("Fujitsu Limited", "Fujitsu Limited", .japanese),
    "4C": ("Sony Corporation", "Sony Corporation", .japanese),
    "4E": ("Teac Corporation", "Teac Corporation", .japanese),
    "50": ("Matsushita Electric Industrial Co. , Ltd", "Matsushita Electric Industrial Co. , Ltd", .japanese),
    "51": ("Fostex Corporation", "Fostex Corporation", .japanese),
    "52": ("Zoom Corporation", "Zoom Corporation", .japanese),
    "54": ("Matsushita Communication Industrial Co., Ltd.", "Matsushita Communication Industrial Co., Ltd.", .japanese),
    "55": ("Suzuki Musical Instruments MFG. Co., Ltd.", "Suzuki Musical Instruments MFG. Co., Ltd.", .japanese),
    "56": ("Fuji Sound Corporation Ltd.", "Fuji Sound Corporation Ltd.", .japanese),
    "57": ("Acoustic Technical Laboratory, Inc.", "Acoustic Technical Laboratory, Inc.", .japanese),
    "59": ("Faith, Inc.", "Faith, Inc.", .japanese),
    "5A": ("Internet Corporation", "Internet Corporation", .japanese),
    "5C": ("Seekers Co. Ltd.", "Seekers Co. Ltd.", .japanese),
    "5F": ("SD Card Association", "SD Card Association", .japanese),
    "004000": ("Crimson Technology Inc.", "Crimson Technology Inc.", .japanese),
    "004001": ("Softbank Mobile Corp", "Softbank Mobile Corp", .japanese),
    "004003": ("D&M Holdings Inc.", "D&M Holdings Inc.", .japanese),
]
